config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#root"

  get "login" => "sessions#new"
  get "sign_up" => "users#new"
  resource :session, only: [:create, :destroy, :new]
  resources :users, only: [:create, :new]

  namespace :api, defaults: { format: :json } do
    resources :food_items, only: [:index, :show]
    resources :restaurants, only: [:index, :show]
    resources :cuisines, only: [:index]
    resources :categories, only: [:index, :show]
    resources :users, only: [:show]
    resources :likes, only: [:create, :destroy]
    resources :reviews, only: [:create, :update, :destroy, :index, :show]
    get "user_likes" => "likes#user_index"
  end
end

app/views/shared/_sign_in_form.html.erb
<% action_url = type == :new_user ? users_url : session_url %>
<% submit_text = type == :new_user ? "Sign Up" : "Log In" %>
<% username_value = type == :new_user ? "user.username" : "" %>

<form action="<%= action_url %>" method="post">
  <%= auth_token_input %>

  <% if type == :new_user %>
    <div class="input-group input-group-lg">
      <input class="form-control"
             id="user_first_name"
             type="text"
             placeholder="First name"
             name="user[first_name]"
             value="<%= user.first_name %>"
             required autofocus>
    </div>
    <% if @user.errors[:first_name].any? %>
      <div class="static-errors-container flash">
        <div class="alert-danger">
          First name <%= @user.errors[:first_name].first %>
        </div>
      </div>
    <% end %>

    <div class="input-group input-group-lg">
      <input class="form-control"
             id="user_last_name"
             type="text"
             placeholder="Last name"
             name="user[last_name]"
             value="<%= user.last_name %>">
    </div>
    <% if @user.errors[:last_name].any? %>
      <div class="static-errors-container flash">
        <div class="alert-danger">
          Last name <%= @user.errors[:last_name].first %>
        </div>
      </div>
    <% end %>

    <div class="input-group input-group-lg">
      <span class="input-group-addon">
        <span class="glyphicon glyphicon-envelope"></span>
      </span>
      <input class="form-control"
             id="user_email"
             type="text"
             placeholder="Email"
             name="user[email]"
             value="<%= user.email %>">
    </div>
    <% if @user.errors[:email].any? %>
      <div class="static-errors-container flash">
        <div class="alert-danger">
          Email <%= @user.errors[:email].first %>
        </div>
      </div>
    <% end %>
  <% end %>

    <div class="input-group input-group-lg">
      <span class="input-group-addon">
        <span class="glyphicon glyphicon-user"></span>
      </span>
      <input class="form-control"
             id="username"
             type="text"
             name="user[username]"
             placeholder="Username">
    </div>
    <% if type == :new_user %>
      <% if @user.errors[:username].any? %>
        <div class="static-errors-container flash">
          <div class="alert-danger">
            Username <%= @user.errors[:username].first %>
          </div>
        </div>
      <% end %>
    <% end %>

    <div class="input-group input-group-lg">
      <span class="input-group-addon">
        <span class="glyphicon glyphicon-lock"></span>
      </span>
      <input class="form-control"
             id="password"
             type="password"
             placeholder="Password"
             name="user[password]">
    </div>
    <% if type == :new_user %>
      <% if @user.errors[:password].any? %>
        <div class="static-errors-container flash">
          <div class="alert-danger">
            Password <%= @user.errors[:password].first %>
          </div>
        </div>
      <% end %>
    <% else %>
    <% if flash[:errors].present? %>
        <div class="static-errors-container flash">
          <div class="alert-danger">
            <%= flash[:errors].first %>
          </div>
        </div>
      <% end %>
    <% end %>

  <% if type == :new_user %>
    <div class="input-group input-group-lg">
      <span class="input-group-addon">
        <span class="glyphicon glyphicon-lock"></span>
      </span>
      <input class="form-control"
             id="password-confirm"
             type="password"
             placeholder="Confirm password"
             name="user[password_confirmation]">
    </div>
    <% if @user.errors[:password_confirmation].any? %>
      <div class="static-errors-container flash">
        <div class="alert-danger">
          Confirmation <%= @user.errors[:password_confirmation].first %>
        </div>
      </div>
    <% end %>
  <% end %>

  <input id="submit-login" class="btn" type="submit" value="<%= submit_text %>">
</form>